### ISSUE TITLE
What about renaming PuzzleApplicationBootstrapper in ApplicationBootstrapper?

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical.Windows.Presentation#21]
> or at least adding a shortcut if it's possibile, just because we would like to have the `PuzzleApplicationBootstrapper` our default easy peasy container, so it could be cool to have it named ApplicationBootstrapper and probably under `Radical.Windows` namespace.
> 
> I saw doing such things in new frameworks out there (like EF7), they use to add the entry point class/methods in the very first namespace where they belong to (eg.: `Microsoft.Data.Entity`), to avoid searching the right namespace to add, and it could also be great to have extension method to enable different containers, so to have something like:
> 
> ``` csharp
> using Radical.Windows;
> var bootstrapper = new ApplicationBootstrapper<Presentation.MainView>();
> ```
> 
> when using just the internal container (puzzle), or this:
> 
> ``` csharp
> using Radical.Windows;
> var bootstrapper = new ApplicationBootstrapper<Presentation.MainView>().UseCastleWindsor();
> ```
> 
> you see, the same namespace is imported `Radical.Windows`, and you have only to add the proper nuget package to have in the same namespace the extension method `UseCastleWindsor()`, so no need to find in other namespace.
> 
> how cool could it be? :smile: 

Inherited from https://github.com/RadicalFx/radical-universal/issues/28
Related to #9

**Comment by mauroservienti** [comment]
@micdenny the [PR](https://github.com/RadicalFx/radical-universal/pull/32) for UWP is ready, was a fairly easy exercise.

On the full fx things are a bit more complex if we do not want to introduce any breaking change. We are faced with 2 options:
1. Introduce a breaking change in `Radical.Windows.Presentation` and all downstream packages simplifying the entire codebase but forcing users to update to the latest and breaking their boot code
2. `Obsolete` the old API and create the new one so that it is backward compatible so that:
   - users can upgrade the `Radical.Windows.Presentation` package only
   - we don't change anything in any downstream repo
   - we can add the new API to side by side in downstream repo as well, obsoleting the old one but not breaking any user code

I absolutely prefer (2) even if more complex and prone to errors. Thoughts?

**Comment by micdenny** [comment]
I would go with (2), so you're thinking to:
1. avoid renaming/remove class, instead obsolete them, add a class `ApplicationBootstrapper` that simply use an instance of `PuzzleApplicationBootstrapper` (similar to what done in UWP)
2. add in the Radical Castle package the extension method to add the castle over the basic puzzle implementation to achieve this `new ApplicationBootstrapper<Presentation.MainView>().UseCastleWindsor();`

**Comment by mauroservienti** [comment]
Yes, correct. The I idea is that you can safely upgrade to the latest without breaking anything, you'll get `Obsolete` warnings only. More important you can decide to upgrade `Radical.Windows.Presentation` only without upgrading the specific container package and we should not fail.

**Comment by micdenny** [comment]
:+1:

**Comment by mauroservienti** [comment]
I have an implementation working locally that depends on https://github.com/RadicalFx/Radical/pull/209 to move forward.

**Comment by mauroservienti** [comment]
Depends on https://github.com/RadicalFx/Radical/issues/20

**Comment by mauroservienti** [comment]
the [PR](https://github.com/RadicalFx/Radical.Windows.Presentation/issues/23) is a blocker for the release. I'll remove this from the milestone. Given the decision to handle https://github.com/RadicalFx/housekeeping/issues/34 as a prerequisite for this.

**Comment by mauroservienti** [comment]
Withdrawing this as we moved to `IServiceCollection` as a mediator between Radical and IoC containers.
