### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical.Windows.Presentation#27]
this is getting ridiculous. Another build failure on a different project but due to the same missing assembly, `Radical.Windows`.

https://ci.appveyor.com/project/radical-bot/radical-windows-presentation

**Comment by mauroservienti** [comment]
@micdenny thoughts?

**Comment by micdenny** [comment]
I will give it a look ASAP

**Comment by mauroservienti** [comment]
this seems to be fixed based on the latest changes I made to `Radical.Windows`, I'll close for now.
