### ISSUE TITLE
TabControlRegion should be able to automatically activate the first tab if there is none

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical.Windows.Presentation#57]
When adding a region a to a `TabControlRegion` and there are no other regions the new region is not rendered until it’s activated. A configuration option should be introduced to change this behavior.

**Comment by nazarenomanco** [comment]
@mauroservienti how do you suggest to add this configuration option for example in: 

`<TabControl Grid.Row="1"  rg:RegionService.Region="{rg:TabControlRegion Name=MainTabRegion}" />`

?

**Comment by mauroservienti** [comment]
By adding a public property to the `TabControlRegion` class we can allow this:

`<TabControl Grid.Row="1"  rg:RegionService.Region="{rg:TabControlRegion Name=MainTabRegion, AutoActivateFirstTab=true}" />`

The `AutoActivateFirstTab` default value should be `false` for backward compatibility. And then the logic should be here https://github.com/RadicalFx/Radical.Windows.Presentation/blob/develop/src/net40/Radical.Windows.Presentation/Regions/Specialized/TabControlRegion.cs#L35

**Comment by mauroservienti** [comment]
A similar thing should be applied on remove, and the first tab, or the previous one should be activated, if configured to do so.

**Comment by mauroservienti** [comment]
Fixed by https://github.com/RadicalFx/Radical.Windows.Presentation/commit/73e4d6cd189aa5c8d05ac546f0b3369a3172a53d
